const mongoose=require('mongoose')
const validator=require('validator');
const RegistrationSchema=new mongoose.Schema({
    Cname:{
        type:String,
        required:true,
        lowercase:true,
        trim: true
    },
    Fname:{
        type:String,
        required:true,
        lowercase:true
    },
    gender:{
        type:String,
        required:true,
    },
    adrs:{
        type:String,
        required:true,
    },
    Fphone:{
        type:Number,
        required:true,
    },
    Cphone:{
        type:Number,
        required:true,
    },
    email:{
        type:String,
        unique:true,
        validate(value)
        {
            if(!validator.isEmail(value))
            {
                throw new Error("Invalid Email");
            }
        }
    },
    Exam10:{
        type:String,
        required:true
    },
    Boarduniversity10:{
        type:String,
        required:true
    },
    Year10:{
        type:Number,
        required:true
    },
    Perc10:{
        type:Number,
        required:true
    },
    Exam12:{
        type:String,
        required:true
    },
    Boarduniversity12:{
        type:String,
        required:true
    },
    Year12:{
        type:Number,
        required:true
    },
    Perc12:{
        type:Number,
        required:true
    },
    Graduate:{
        type:String,
        required:true
    },
    University:{
        type:String,
        required:true  
    },
    YearGrad:{
        type:Number,
        required:true
    },
    PerGrad:{
        type:Number,
        required:true
    },
    Others:{
        type:String,
    },
    BUOthers:{
        type:String,
    },
    YearOthers:{
        type:Number,
    },
    PerOthers:{
        type:Number,
    },
    Interst:{
        type:String,
        required:true
    },
    campus:{
        type:String,
        required:true
    },
    exam:{
        type:String
    },
    cmrno:{
        type:String
    },
    cmscore:{
        type:String
    },
    know:{
        type:String,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    date:{
        type:Date,
         default:Date.now
       }

})

module.exports=mongoose.model("Registration",RegistrationSchema);